data_ingestion:
  root_dir:  data/raw
  source_URL: https://datascientest-mlops.s3.eu-west-1.amazonaws.com/mlops_dvc_fr/raw.csv
  local_data_file: data/raw/raw.csv

data_preparation: 
  root_dir: data/processed
  data_path: data/raw/raw.csv
  target: 'silica_concentrate' 
  test_size: 0.3

data_transformation: 
  root_dir: data/processed
  data_path: data/processed

model_trainer:
  root_dir: models
  X_train_path: data/processed/X_train.csv
  X_test_path: data/processed/X_test.csv
  y_train_path: data/processed/y_train.csv
  y_test_path: data/processed/y_test.csv
  model_name: model.joblib

model_evaluation:
  root_dir: metrics
  X_test_path: data/processed/X_test.csv
  y_test_path: data/processed/y_test.csv
  model_path: models/model.joblib
  metric_file_name: metrics/metrics.json
